PokemonTCG/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("pokemondb/", include("pokemondb.urls")),
    path("accounts/", include("accounts.urls")), 
    path("tcg_api/", include("tcg_api.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("collection/", include("collection.urls")),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    
]

pokemondb/urls.py
from django.urls import path
from .views import pokemondb_homepage_view, pokemondb_search_results_view, filter_cards, pokemondb_gallery_view, pokemondb_toggle_card_in_collection


app_name = "pokemondb"
urlpatterns = [
    path('home/', pokemondb_homepage_view.as_view(), name='homepage'),
    path('search/', pokemondb_search_results_view.as_view(), name='search_results'),
    path('filter/', filter_cards, name='filter'),
    path('gallery/', pokemondb_gallery_view.as_view(), name='gallery'),
    path('toggle_ownership/', pokemondb_toggle_card_in_collection.as_view(), name='toggle_ownership'),
]

tcg_api/urls.py
from django.urls import path
from . import views

app_name = "tcg_api"
urlpatterns = [
    path('cards/', views.card_list, name='card_list'),
]

pokemondb/models.py
from django.db import models
import django_filters

#creates table categories for the card database
class Card(models.Model):
    # name of the card (ie:bulbasaur, pokemon_catcher)
    name = models.CharField(max_length=100, default="bulbasaur")

    # the set the card came from (ie:twilight_masquerade)
    collection = models.CharField(max_length=100, default="twilight_masquerade")

    # the category of the card NOT THE POKEMON TYPE (ie: supporter, pokemon)
    card_type = models.CharField(max_length=50, default="item")

    # the pokemon's type (ie: grass) trainers are empty
    element_type = models.CharField(max_length=50, default="trainer")

    # the card image
    image = models.CharField(max_length=128, default="images/1-Venusaur-ex-Stellar-Crown.png")

    # the pokemon's stage (basic=0, trainer=null)
    stage = models.SmallIntegerField(null=True)

    # the pokemon's hp (trainer=null)
    hp = models.IntegerField(null=True)

    # the pokemon's suffix if applicable (ie:ex, v, vstar)
    suffix = models.CharField(max_length=20, default="")

    #the dumb card number cause sam said so
    card_number = models.IntegerField(default=0)

    #id to be used when calling the API
    set_id = models.CharField(max_length=30, default="sv7")

    def __str__(self):
        return self.name
    

pokemondb/views.py
from itertools import zip_longest
import json
from typing import Any
from django.http import HttpResponse, JsonResponse
from django.views import View
from django.views.generic import TemplateView, ListView
from django.db import models
from .models import Card
from tcg_api.models import API_cards
from accounts.models import CustomUser
from django.db.models import Q
from django.shortcuts import render
from .filters import CardFilter
from django.core.management import call_command

# Create your views here.
class pokemondb_homepage_view(TemplateView):
    template_name = "pokemondb/homepage.html"

    #function to add a 'greeting' that can be used in the HTML template (this will likely be changed later to information that is more useful than a greeting)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['greeting'] = 'Welcome to my homepage!'
        return context
    
class pokemondb_gallery_view(TemplateView):
    template_name = 'pokemondb/gallery.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['message'] = 'Welcome to the gallery!'
        return context

    def get(self, request):
        if (not API_cards.objects.exists()):
            call_fetch_cards(request)
        #test case to make sure only cards in list show set to True to display owned cards
        show_owned = request.GET.get('toggle-ownership-filter') == 'true'  # Will be True if checked, False if not
        card_list = Card.objects.all()
        api_list = API_cards.objects.all()

        
        
        current_user = request.user
        if show_owned:
            owned_cards = current_user.listPokemon
            card_list = Card.objects.filter(id__in=owned_cards)
            temp_id_list = []
            for card in card_list:
                temp_id_list.append(card.set_id + "-" + str(card.card_number))
            api_list = API_cards.objects.filter(id__in=temp_id_list)
        
        combined_list = zip(card_list, api_list)

        my_filter = CardFilter(request.GET, queryset=card_list)
        card_list = my_filter.qs

        context = {"card_list":combined_list, "api_list":api_list, "my_filter":my_filter}

        return render(request, "pokemondb/gallery.html", context)

    
class pokemondb_search_results_view(ListView):
    model = Card
    template_name = 'pokemondb/search_results.html'

    def get_queryset(self): # new
        query = self.request.GET.get("q")
        object_list = Card.objects.filter(
            Q(name__icontains = query) | Q(card_number__icontains = query) | Q(collection__icontains = query) 
        )
        return object_list

class pokemondb_toggle_card_in_collection(View):
    def post(self, request, *args, **kwargs):
        data = json.loads(request.body)
        button_id = data.get('buttonId')
        print("Button "+str(button_id)+" pressed!")
        # Perform actions based on button_id

        added = False
        if not request.user.remove_pokemon(button_id):  # If we fail to remove the card (user didn't have it yet)
            request.user.add_pokemon(button_id)         # Then add it to the user!
            added = True

        response_data = {
            'message': f'{"Card added to your collection!" if added else "Card removed from your collection."}',
            'success': True
        }
        return JsonResponse(response_data)

    def get(self, request, *args, **kwargs):
        return JsonResponse({'success': False}, status=400)

def filter_cards(request):
    #test case to make sure only cards in list show set to True to display owned cards
    show_owned = False
    card_list = Card.objects.all()
    current_user = request.user
    if show_owned:
        owned_cards = current_user.listPokemon
        card_list = Card.objects.filter(id__in=owned_cards)
    
    my_filter = CardFilter(request.GET, queryset=card_list)
    card_list = my_filter.qs

    context = {"card_list":card_list, "my_filter":my_filter}

    return render(request, "pokemondb/filter.html", context)

def call_fetch_cards(request):
        call_command('fetch_cards')
        return HttpResponse('Custom command has been executed!')

pokemondb/templates/pokemondb/filter.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<!-- required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<!-- bootstrap CSS -->
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

		<title>Filter Results</title>
	</head>
	<body>
		<h1>Filter Results</h1>

		<br>
			<!-- <div class="row collapse {% if show_form %} show  {% endif %}" id="form-holder"> -->
				<div class="row">
					<div class="col">
						<div class="card card-body">

							<form method="get">
								{{my_filter.form.as_p}}

								<button class="btn-primary" type="submit">Search</button>
							</form>
						</div>
					</div>
				</div>
			<!-- </div> -->
		</br>

		<div class="container">
			<div class="row">
				{% for card in card_list %}
					{% with "pokemondb/"|add:card.image as image %}
						<div class="col-md-4">
							<img class="img-fluid" src="{% static image %}">
						</div>
						{% if forloop.counter|divisibleby:3 and not forloop.last %}
							</div><div class="row"> <!-- Start a new row after every 3 items -->
						{% endif %}
					{% endwith %}
				{% endfor %}
			</div>
		</div>


		<!-- <ul>
			{% for card in card_list %}
				{% with "pokemondb/"|add:card.image as image %}
				<li>
					{{ card.name }}, {{ card.card_number}}, <img src="{% static image %}" alt="">
				</li>
				{% endwith %}
			{% endfor %}
		</ul> -->
	</body>
</html>

pokemondb/templates/pokemondb/gallery.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- required meta tags -->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">

        <!-- bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

        <!--custom css-->
        <link rel="stylesheet" type="text/css" href="{% static 'pokemondb/css/gallery-styles.css' %}">

        <!--google font-->
        <link href="https://fonts.googleapis.com/css2?family=Fredoka:wght@300..700&family=Source+Sans+3:ital,wght@0,200..900;1,200..900&display=swap" rel="stylesheet">
        
        <!--title-->
        <title>Gallery</title>
    </head>
    <body>
        <!--gallery navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #1C486D;">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">
                    <img src="{% static 'pokemondb/assets/pokeball.png' %}" alt="pokeball" width="30" height="30">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link active" aria-current="page" href="{% url 'pokemondb:gallery' %}">Gallery</a>
                    </div>
                </div>
            </div>    
        </nav>
        <br>
        <!--end navbar-->

        <!--container for the search and filter fields-->
        <div class="container-fluid">
            <div class="row mt-3 ms-3 mb-3">
                <div class="col">
                    <form action="/pokemondb/search/" method="get">
                        <input name="q" type="text" placeholder="Search for a specific card...">
                    </form>
                </div>
            </div>
            <div class="row ms-3 mb-3">
                <div class="col">
                    <form method="get">

                        <label>
                            <input type="checkbox" name="toggle-ownership-filter" value="true"> Show owned cards
                        </label>

                        {{my_filter.form.as_p}}
                        <button class="btn-primary" type="submit">Filter</button>
                    </form>
                </div>
            </div>
        </div>
        <br>
        <!--end container-->
 
        <!--container for all of the cards generated in the gallery-->
        <div class="container">
            <div class="row">
                {% for card, price in card_list %}
                    {% with "pokemondb/"|add:card.image as image %}
                        <div class="col-md-4">
                            <img class="img-fluid" src="{% static image %}">
                            <button id="button-1" class="add-to-collection" data-button-id="{{ card.id }}">Add/Remove</button>
                            <p>Current market value: {{ price.trendPrice }}</p>
                        </div>
                        {% if forloop.counter|divisibleby:3 and not forloop.last %}
                            </div><div class="row"> <!-- Start a new row after every 3 items -->
                        {% endif %}
                    {% endwith %}
                {% endfor %}
            </div>
        </div>
        <!--end of card container-->

        <!--boostrap js-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
        <!--button click handler-->
        <script>
            document.querySelectorAll('.add-to-collection').forEach(button => {
                button.addEventListener('click', function() {
                    const buttonId = this.getAttribute('data-button-id');
                    fetch('{% url "pokemondb:toggle_ownership" %}', {
                        method: 'POST',
                        headers: {
                            'X-CSRFToken': '{{ csrf_token }}',
                            'Content-Type': 'application/json'
                        },
                        body: JSON.stringify({ buttonId: buttonId })
                    })
                    .then(response => response.json())
                    .then(data => {
                        alert(data.message);
                    })
                    .catch(error => {
                        alert('An error occurred: ' + error);
                    });
                });
            });
        </script>
    </body>
</html>

pokemondb/templates/pokemondb/homepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <!--required meta tags-->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!--boostrap css-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        
        <!--custom css-->
        <link rel="stylesheet" type="text/css" href="{% static 'pokemondb/css/homepage-styles.css' %}">
        
        <!--google font-->
        <link href="https://fonts.googleapis.com/css2?family=Fredoka:wght@300..700&family=Source+Sans+3:ital,wght@0,200..900;1,200..900&display=swap" rel="stylesheet">
        
        <!--title-->
        <title>Pokemon TCG Database</title>
    </head>
    <body>
        <!--homepage navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #1C486D;">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">
                    <img src="{% static 'accounts/img/pokeball.png' %}" alt="pokeball" width="30" height="30">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link active" aria-current="page" href="{% url 'pokemondb:homepage' %}">Home</a>
                        <a class="nav-link" href="{% url 'pokemondb:gallery' %}">Gallery</a>
                    </div>
                </div>
            </div>
        </nav>
        <!--end navbar-->
        <h1>Hello, Pokemon Homepage!</h1>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </body>
    
</html>

pokemondb/templates/pokemondb/search_results.html
{% load static %}
<h1>Search Results</h1>

<ul>
  {% for card in object_list %}
    {% with "pokemondb/"|add:card.image as image %}
      <li>
        {{ card.name }}, {{ card.card_number}}, <img src="{% static image %}" alt="">
      </li>
    {% endwith %}
  {% endfor %}
</ul>